services:
  network-api:
    build: .
    container_name: network-api
    restart: unless-stopped

    ports:
      - "Your desired port number"

    volumes:
      - .:/app

    working_dir: /app
    environment:
      - MAYA_BEARER_TOKEN=${MAYA_BEARER_TOKEN}
      - MAYA_API_USERNAME=${MAYA_API_USERNAME}
      - MAYA_API_PASSWORD=${MAYA_API_PASSWORD}
      - Name_HOST=${Name_HOST}
      - Name_PORT=${Name_PORT}
      - Name_USERNAME=${Name_USERNAME}
      - Name_PASSWORD=${Name_PASSWORD}
      - Name_HOST=${Name_HOST}
      - Name_PORT=${Name_PORT}
      - Name_USERNAME=${Name_USERNAME}
      - Name_PASSWORD=${Name_PASSWORD}

    networks:
      - maya-network

networks:
  maya-network:
    external: true
