services:
  network-api:
    build: .
    container_name: network-api
    restart: unless-stopped

    ports:
      - "127.0.0.1:3984:8000"

    volumes:
      - .:/app

    working_dir: /app
    environment:
      - MAYA_BEARER_TOKEN=${MAYA_BEARER_TOKEN}
      - MAYA_API_USERNAME=${MAYA_API_USERNAME}
      - MAYA_API_PASSWORD=${MAYA_API_PASSWORD}
      - KINCAR_HOST=${KINCAR_HOST}
      - KINCAR_PORT=${KINCAR_PORT}
      - KINCAR_USERNAME=${KINCAR_USERNAME}
      - KINCAR_PASSWORD=${KINCAR_PASSWORD}
      - KARIOKOR_HOST=${KARIOKOR_HOST}
      - KARIOKOR_PORT=${KARIOKOR_PORT}
      - KARIOKOR_USERNAME=${KARIOKOR_USERNAME}
      - KARIOKOR_PASSWORD=${KARIOKOR_PASSWORD}
      - ALLSOPS_HOST=${ALLSOPS_HOST}
      - ALLSOPS_PORT=${ALLSOPS_PORT}
      - ALLSOPS_USERNAME=${ALLSOPS_USERNAME}
      - ALLSOPS_PASSWORD=${ALLSOPS_PASSWORD}
      - KINCAR_SSH_PORT=${KINCAR_SSH_PORT}
      - KARIOKOR_SSH_PORT=${KARIOKOR_SSH_PORT}
      - ALLSOPS_SSH_PORT=${ALLSOPS_SSH_PORT}
      - GENIEACS_BASE_URL=${GENIEACS_BASE_URL}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_REPO=${GITHUB_REPO}
      - JWT_SECRET=${JWT_SECRET}

    networks:
      - maya-network

networks:
  maya-network:
    external: true
